### ISSUE TITLE
Refactor methods in components/containers

### ISSUE THREAD

**Issue by shannonmoranetz** [dForDeveloper/movie-tracker#11]
- [x] Refactor React Components
- [x] Duplication in methods
- [x] Eliminate queries.js
    - [x] Single fetch call with a dynamic URL
- [x] Break out difficult-to-read render methods

**Comment by dForDeveloper** [comment]
dForDeveloper@855f2c3f2c047b46cbf2348b88c0e80c6f407fea
dForDeveloper@0133b65bf5cf01fed8f9394008ece9d5e2236d11
