### ISSUE TITLE
Iteration 1: Sign In / Sign Out Functionality

### ISSUE THREAD

**Issue by shannonmoranetz** [dForDeveloper/movie-tracker#15]
- [x] Be able to sign in on page /login and redirect user to /
- [x] Flash "Email and Password do not match" - if password is incorrect
- [x] Ability to create a user.
- [x] Flash "Email has already been used" - if email has been taken
- [x] The user has the ability to sign out.

**Comment by dForDeveloper** [comment]
dForDeveloper@d803860e7e3dd5a94c9e7706dc5794da19186443
dForDeveloper@b618f23da9ef59f1c8b4bec756655c3be9a4ffa4
a966c8d9ac2ea00952019c61f34f1f2d6ae7fb61
dForDeveloper@4b31b660fd233f1fb37a522d15adf604384b806e
cab761bdf31b87103adee21834de73effb413570
91127146500fb7148c16f4695aebaecc6b628349
f65aeb0bc8ca25ce6b8ad769fd4296eb0f28d6d9
dForDeveloper@b6af46c1c6c36b7c70c83104f8f5242109d2508d
