### ISSUE TITLE
Iteration 2: Favorites and Showing Details

### ISSUE THREAD

**Issue by shannonmoranetz** [dForDeveloper/movie-tracker#16]
- [x] Each movie should be displayed with a favorite button.
- [x] If the user is not signed in and clicks on a favorite button the user will be prompted with the request to create an account.
- [x] Validate favorites before adding to db. Aka does that user already have the movie stored as favorites. There should be no duplicates.
- [x] If the user visits /favorites they should see a list of all their favorite movies.
- [x] The user should be able to delete favorites from /favorites or /.
- [x] Favorite movies should have a visual indication on /.
- [x] A user can click and view any individual movie. The url for each individual movie page should be "/movies/:id"

**Comment by dForDeveloper** [comment]
dForDeveloper@00e64affb35f3ae08b84d3e2315b2baca0354b83
dForDeveloper@fd3cd041740ad9a9085a97e502ea1f56f9f42eee
558e94dec5ff0c8d9d0da92d9ee78c20f077ee81
dForDeveloper@55adde9a157d0b7963e60acbdfd7c07a2d30469c
dForDeveloper@bed5aa994bc8dd3c79dd1e58657a9431e4f90cc3
