### ISSUE TITLE
Implement PropTypes

### ISSUE THREAD

**Issue by shannonmoranetz** [dForDeveloper/movie-tracker#4]
- [x] Implement propTypes on all components/containers that require them
    - [x] Install prop-types module:
        - [x] https://www.npmjs.com/package/prop-types
    - [x] Import proptypes on components/containers
        - [x] Specify propTypes per each component/container

**Comment by dForDeveloper** [comment]
dForDeveloper@69112b506689c3d3fd04860685322cf5d48d2ec4
