### ISSUE TITLE
Show movie details upon clicking a movie item

### ISSUE THREAD

**Issue by shannonmoranetz** [dForDeveloper/movie-tracker#5]
- [x] Create all related files
    - Functional component
- [x] Component returns all necessary details per each movie item
    - [x] Title, image, overview, release date, rating
- [x] Route to URL of each movie ID
    - [x] Path should go to: /movies/:id
    - [x] Route in App container

**Comment by dForDeveloper** [comment]
dForDeveloper@bed5aa994bc8dd3c79dd1e58657a9431e4f90cc3
